---
- name: Check that a page returns a status 200 and fail if the word AWESOME is not in the page contents
  uri:
    url: https://circleci-binary-releases.s3.amazonaws.com/circleci-launch-agent/release.txt
    return_content: yes
  register: release_info

- name: Setting Launch Agent Version
  set_fact:
    launch_agent_version: "{{ release_info.content[:-1] }}"
  when: RUNNER_VERSION == None and SERVER_INSTALL == False

- include_tasks: linux-setup.yml
  when: ansible_system == "Linux"

- include_tasks: windows-setup.yml
  when: ansible_system == "Windows"

- include_tasks: darwin-setup.yml
  when: ansible_system == "Darwin" 
